name: DevSecOps Quality & Security Pipeline

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  quality-check:
    name: Lint & Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode sumber
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Jalankan ESLint
        run: npm run lint

      - name: Jalankan Unit Tests
        run: npm test -- --watchAll=false

      - name: Upload Coverage Report
        run: npm run test:coverage

  sast-scan:
    name: SAST (Semgrep)
    runs-on: ubuntu-latest
    needs: quality-check
    steps:
      - uses: actions/checkout@v4
      - name: Jalankan Semgrep SAST
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/default
            p/javascript
            p/react

  sca-scan:
    name: SCA (Dependency Check)
    runs-on: ubuntu-latest
    needs: quality-check
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Audit npm dependencies
        run: npm audit --audit-level=high || true

  build:
    name: Build Production
    runs-on: ubuntu-latest
    needs: [sast-scan, sca-scan]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install & Build
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: build/